# Build stage
FROM node:20-alpine AS builder
RUN apk update
RUN apk add git
WORKDIR /app
RUN git clone https://github.com/jankiz/nodejs-sample-app-for-devops.git
WORKDIR /app/nodejs-sample-app-for-devops
RUN git checkout feature/http-server
RUN npm ci
RUN npm run build

# Production stage
FROM node:20-alpine
RUN npm install -g pm2
RUN apk add curl
WORKDIR /app
COPY --from=builder /app/nodejs-sample-app-for-devops/dist ./dist
COPY --from=builder /app/nodejs-sample-app-for-devops/package*.json ./
RUN npm ci --only=production && npm cache clean --force
EXPOSE 3000
CMD ["pm2-runtime", "start", "dist/index.js"]

# http://localhost:3000/add?num1=10&num2=20