# Build stage
FROM node:20-alpine AS builder
RUN apk update
RUN apk add git
WORKDIR /app
RUN git clone https://github.com/Tibi1210/NodeApp.git
WORKDIR /app/nodejs-sample-app-for-devops
RUN git checkout feature/monitoring
RUN npm ci
RUN npm run build

# Production stage
FROM node:20-alpine
RUN npm install -g pm2
RUN apk add curl

# Install rsyslog
RUN apk add --no-cache rsyslog
# Create rsyslog config
COPY rsyslog.conf /etc/rsyslog.conf
RUN mkdir -p /var/log/pm2
# Configure PM2 to use syslog
ENV PM2_SYSLOG=true

WORKDIR /app
COPY --from=builder /app/nodejs-sample-app-for-devops/dist ./dist
COPY --from=builder /app/nodejs-sample-app-for-devops/package*.json ./
COPY --from=builder /app/nodejs-sample-app-for-devops/start.sh ./
RUN npm ci --only=production && npm cache clean --force
EXPOSE 3000

RUN chmod +x start.sh
CMD ["./start.sh"]
# http://localhost:3000/add?num1=10&num2=20