FROM python:3.9-slim

WORKDIR /app

COPY test.py .

EXPOSE 2000

CMD python test.py

# docker build -t nodejs-sample-app -f Dockerfile .
# docker run -it --rm -p 3000:3000 nodejs-sample-app
# http://localhost:2000/